font_path:
    - C:\P-ROC\shared\dmd\
    - ./assets/dmd/
config_path:
    - C:\P-ROC\shared\config\
dmd_path: ./assets/dmd/
sound_path: ./assets/sound/
voice_dir: voice/ # i.e., this is assets/sound/voice/
sfx_dir: sfx/
music_dir: music/
hdfont_path: ./assets/fonts/

pinproc_class: procgame.fakepinproc.FakePinPROC # comment out this line when using a real P-ROC. 

use_desktop: True
color_desktop: True

vp_game_map_file: C:\P-ROC\shared\vp_game_map.yaml  # relevant for Visual Pinball (only) # Change this to where you create your map file

keyboard_switch_map:
    # Enter, Up, Down, Exit
    7: enter
    8: down
    9: up
    0: exit
    # Start:
    q: leftOutlane
    w: rightReturnLane
    e: rightOutlane
    r: bottomRightStandUp
    t: beerMug
    y: topRightStandUp
    u: rightSlingshot
    i: leftJetBumper
    o: rightJetBumper
    c: rightLoopTop
    a: rightBonusLane
    s: startButton #SD15
    d: rightRampMake
    f: rightRampEnter
    g: saloonBart
    h: leftLoopTop
    j: leftRampEnter
    k: minePopper
    l: centerRampMake
    z: shooterLane
    x: mineEntrance
    c: troughEject
    v: skillBowl
    b: saloonGate
    n: centerRampMake
    m: badGuySW2
